# Site settings
title: deathwheadfish
tag_text:
description:
ga_id: UA-102012759-1
paginate: 20
paginate_path: archive/:num

permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown

exclude: ["README.md"]
